# Streaming Profile
[protocol.http]
profile-restore=copy-equal
cache=yes
cache-secs=30
video-sync=audio
interpolation=no

[protocol.https]
profile=protocol.http

[protocol.ytdl]
profile=protocol.http

# Shaders Presets
[ravu]
profile-desc="RAVU Lite traditional upscaling"
glsl-shaders="~~/shaders/ravu-lite-ar-r4.hook;~~/shaders/noise-static-luma.hook"

[ravu_zoom]
profile-desc="RAVU Zoom for cropped content"
glsl-shaders="~~/shaders/ravu-zoom-ar-r3.hook;~~/shaders/noise-static-luma.hook"

[ArtCNN_C4F16]
profile-desc="AI upscaling with 16 filters (balanced)"
glsl-shaders="~~/shaders/ArtCNN_C4F16.glsl;~~/shaders/Adaptive-Sharpen.glsl"

[ArtCNN_C4F32]
profile-desc="AI upscaling with 32 filters (high quality)"
glsl-shaders="~~/shaders/ArtCNN_C4F32.glsl;~~/shaders/Adaptive-Sharpen.glsl"

# Profiles based on release
[simulcast]
profile-cond=filename~=nil and (function(a)for b,c in ipairs(a)do if filename:match(c)then return true end end end)({"SubsPlease","Erai%-raws","Tsundere%-Raws","%-VARYG","HorribleSubs","SubsPlus%+","Yameii"})
profile=ArtCNN_C4F16
sub-ass-use-video-data=aspect-ratio
deband=yes

[WebDL]
profile-cond=p.filename~=nil and string.match(p.filename, "%[Web%-DL%]")~=nil
profile=ArtCNN_C4F16
deband=no
sub-ass-use-video-data=aspect-ratio