# Streaming Profiles
[protocol.http]
profile-restore=copy-equal
cache=yes
cache-secs=120
video-sync=audio
interpolation=no

[protocol.https]
profile=protocol.http

[protocol.ytdl]
profile=protocol.http

# Shaders Profiles
[ravu]
profile-desc="RAVU Lite traditional upscaling"
glsl-shaders="~~/shaders/ravu-lite-ar-r4.hook;~~/shaders/noise-static-luma.hook"

[ravu_zoom]
profile-desc="RAVU Zoom for cropped content"
glsl-shaders="~~/shaders/ravu-zoom-ar-r3.hook;~~/shaders/noise-static-luma.hook"

[ArtCNN_C4F16]
profile-desc="AI upscaling with 16 filters (balanced)"
glsl-shaders="~~/shaders/ArtCNN_C4F16.glsl;~~/shaders/Adaptive-Sharpen.glsl"

[ArtCNN_C4F32]
profile-desc="AI upscaling with 32 filters (high quality)"
glsl-shaders="~~/shaders/ArtCNN_C4F32.glsl;~~/shaders/Adaptive-Sharpen.glsl"

[debrid]
profile-cond=filename~=nil and (string.match(filename, "[?&]token=")~=nil or string.match(filename, "^https?://.-%?")~=nil)
profile=protocol.http
glsl-shaders="~~/shaders/ArtCNN_C4F16.glsl;~~/shaders/Adaptive-Sharpen.glsl"
save-position-on-quit=no
