# restyle subtitles by pressing k
k cycle_values sub-ass-override "force" "no"

\ show-text ${glsl-shaders}

CTRL+0 no-osd change-list glsl-shaders clr ""; show-text "GLSL shaders cleared"
CTRL+1 no-osd change-list glsl-shaders set "~~/shaders/ArtCNN_C4F16.glsl;~~/shaders/Adaptive-Sharpen.glsl"; show-text "ArtCNN C4F16 + Adaptive Sharpen"
CTRL+2 no-osd change-list glsl-shaders set "~~/shaders/ArtCNN_C4F32.glsl;~~/shaders/Adaptive-Sharpen.glsl"; show-text "ArtCNN C4F32 + Adaptive Sharpen"
CTRL+3 no-osd change-list glsl-shaders set "~~/shaders/ravu-lite-ar-r4.hook;~~/shaders/noise-static-luma.hook"; show-text "Ravu Lite AR R4 + Noise Static Luma"
CTRL+4 no-osd change-list glsl-shaders set "~~/shaders/ravu-zoom-ar-r3.hook;~~/shaders/noise-static-luma.hook"; show-text "Ravu Zoom AR R3 + Noise Static Luma"


MBTN_LEFT           script-binding evafast/speedup      #event: press
MBTN_LEFT           script-binding evafast/slowdown     #event: release
MOUSE_MOVE          ignore