### General ###

include="~~/mpv-opts/general.conf"

### OSD ###

include="~~/mpv-opts/osd.conf"

### Screenshots ###

include="~~/mpv-opts/screenshot.conf"

### Video ###

include="~~/mpv-opts/video.conf"

### Audio ###

include="~~/mpv-opts/audio.conf"

### Subtitles ###

include="~~/mpv-opts/subtitle.conf"
include="~~/font-opts/netflix.conf"
#include="~~/font-opts/rosario.conf"

### Deband ###

include="~~/mpv-opts/deband.conf"

### Display ###

include="~~/mpv-opts/display.conf"

### Language Priority ###

include="~~/mpv-opts/lang.conf"

### Profiles ###

include="~~/mpv-opts/profiles.conf"

### Shaders ###

include="~~/mpv-opts/shaders.conf"