profile=high-quality

### Video Output ###
vo=gpu-next
gpu-api=vulkan
hwdec=nvdec

### Color & HDR ###
tone-mapping=st2094-40
target-colorspace-hint=no

### Debanding ###
deband=no
deband-iterations=2
deband-threshold=32
deband-range=16
deband-grain=0

### Dithering ###
dither-depth=10

### Interpolation ###
video-sync=display-resample
interpolation=yes
tscale=oversample

### Window ###
no-border
osc=no
snap-window
autofit=50%
cursor-autohide=500

### OSD ###
osd-bar=no
osd-bold=yes
osd-font-size=37
osd-font='Inter'

### Playback ###
keep-open=no
save-position-on-quit=yes
force-seekable=yes

### Audio ###
volume=100
volume-max=120
audio-file-auto=fuzzy
audio-exclusive=no
audio-channels=auto

### Subtitles ###
slang=eng,en,enUS,English
alang=ja,jp,jpn,jap,Japanese,eng,en,enUS,English
demuxer-mkv-subtitle-preroll=yes
sub-auto=fuzzy
sub-ass-override=no
sub-ass-style-overrides=playresx=1920,playresy=1080,Kerning=yes
sub-margin-x=100
sub-margin-y=40

# --- Carlito (default) ---
sub-font=Carlito
sub-font-size=52
sub-blur=0.1
sub-color="#FFFFFF"
sub-border-size=3.2
sub-border-color="#FF000000"
sub-shadow-color="#A0000000"
sub-shadow-offset=0.5
sub-bold=yes

# --- Netflix Sans (uncomment to use) ---
#sub-font="Netflix Sans Bold"
#sub-font-size=48
#sub-color="#FFFFFF"
#sub-margin-y=40
#sub-border-size=2.0
#sub-border-color="#FF000000"
#sub-shadow-color="#A0000000"
#sub-shadow-offset=1.2
#sub-line-spacing=0.9

### Screenshots ###
screenshot-dir="~~/cache/screenshots"
screenshot-template="%F-%p"
screenshot-format=png
screenshot-high-bit-depth=yes

### Paths & Cache ###
watch-later-dir="~~/cache/watch_later"
gpu-shader-cache-dir="~~/cache/shaders_cache"
log-file="~~/cache/logs/mpv.log"

### Includes ###
include="~~/auto-profiles.conf"