osc=no
keep-open=yes
save-position-on-quit=yes
autofit=50%
force-seekable=yes
cursor-autohide=500
watch-later-dir="~~/cache/watch_later"
gpu-shader-cache-dir="~~/cache/shaders_cache"
log-file=~~/cache/logs/mpv.log