[Crunchyroll]
profile-cond=filename:match("SubsPlease") or filename:match("Erai%-raws") or filename:match("HorribleSubs")
profile-restore=copy
profile=ArtCNN_C4F16
sub-ass-use-video-data=aspect-ratio

[Simulcast]
profile-cond=(function(a)for b,c in ipairs(a)do if filename:match(c)then return true end end end)({"SubsPlease","Erai%-raws","Tsundere%-Raws","%-VARYG","HorribleSubs","SubsPlus%+"})
profile-restore=copy
sub-ass-override=force
deband=yes

[WebDL]
profile-cond=string.match(p.filename, "%[Web%-DL%]")~=nil
deband=yes
sub-ass-use-video-data=aspect-ratio

[Deband]
profile-cond=p["video-params/pixelformat"] == "yuv420p"
deband=yes

[Dolby Vision On]
target-trc=pq
target-prim=bt.2020

[Dolby Vision Off]
target-trc=auto
target-prim=auto