[ArtCNN_C4F16]
glsl-shaders="~~/shaders/ArtCNN_C4F16.glsl;~~/shaders/Adaptive-Sharpen.glsl"

[ArtCNN_C4F32]
glsl-shaders="~~/shaders/ArtCNN_C4F32.glsl;~~/shaders/Adaptive-Sharpen.glsl"

[ravu]
glsl-shaders="~~/shaders/ravu-lite-ar-r4.hook;~~/shaders/noise-static-luma.hook"