demuxer-mkv-subtitle-preroll=yes
#sub-ass-use-video-data=aspect-ratio
sub-auto=fuzzy
sub-ass-override=no
subs-with-matching-audio=no
blend-subtitles=yes
sub-fix-timing=yes
sub-gauss=1.0
sub-gray=yes
sub-scale-by-window=yes