# sub-ass-override=no
# sub-ass-style-overrides=playresx=1920,playresy=1080,Kerning=yes
# sub-font="Netflix Sans Bold"
# sub-font-size=50
# sub-color="#FFFFFF"
# sub-margin-y=40
# sub-border-size=3.0
# sub-border-color="#FF000000"
# sub-shadow-color="#A0000000"
# sub-shadow-offset=1.2
sub-ass-override=no
sub-ass-style-overrides=playresx=1920,playresy=1080,Kerning=yes
sub-font="Netflix Sans Bold"
sub-font-size=48
sub-color="#FFFFFF"
sub-align=5 
sub-margin-y=50
sub-border-size=2.0
sub-line-spacing=0.9
sub-border-color="#FF000000"
sub-shadow-color="#A0000000"
sub-shadow-offset=1.2