sub-ass-override=no
sub-ass-style-overrides=playresx=1920,playresy=1080,Kerning=yes
sub-font="Rosario Bold"
sub-font-size=60
sub-color="#FFFFFF"
sub-margin-y=40
sub-border-size=2.4
sub-border-color="#FF000000"
sub-shadow-color="#A0000000"
sub-shadow-offset=0.75